name: build

on: 
#  push:
#    branches:
#    - "*"
  workflow_dispatch:
    inputs:
      target:
        type: choice
        description: 'Please select the model to compile'
        options:
        - 'B70'
        - 'BELL-A040WQ'
        - 'CR660x'
        - 'DIR-878'
        - 'DIR-882'
        - 'EA7500'
        - 'E8820V2'
        - 'GHL'
        - 'JCG-836PRO'
        - 'JCG-AC860M'
        - 'JCG-Q20-PB'
        - 'JCG-Q20'
        - 'JCG-Y2'
        - 'K2P-USB'
        - 'K2P-NANO'
        - 'K2P'
        - 'MI-4'
        - 'MI-R3G'
        - 'MI-R3P-PB'
        - 'MI-R3P-SPI'
        - 'MI-R3P'
        - 'MI-R4A'
        - 'MR2600'
        - 'MSG1500'
        - 'MSG1500-Z'
        - 'NETGEAR-BZV'
        - 'NEWIFI'
        - 'NEWIFI3'
        - 'QM-B1'
        - 'R2100'
        - 'R6800'
        - 'RE-CP-02'
        - 'RE-SP-01B'
        - 'RM2100'
        - 'RT-AC85P'
        - 'TX1801'
        - 'WR1200JS'
        - 'XY-C1'
        - 'ZTE-E8820S'
        - 'WE410443-TC'
        - 'HAR-20S2U1'
        - 'SIM-AX1800T'
        default: 'K2P'
      release:
        type: boolean
        description: 'upload to release'
        default: 'true'
jobs:
  build:
    name: ${{ inputs.target }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hendrikmuhs/ccache-action@v1.2
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          check-latest: true
          cache-dependency-path: '**/go.sum'
      - name: Prepare environment
        run: |
          sudo apt update
          sudo apt install libtool-bin gperf python3-docutils autopoint gettext ccache
      - name: Start Build
        run: |
          make ${{ inputs.target }}
          echo "TAG_ANME=$(date +%Y%m%d)" >> $GITHUB_ENV
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.target }}-${{ env.TAG_ANME }}
          path: trunk/images/*.trx
      - uses: ncipollo/release-action@v1
        if: github.event.inputs.release == 'true'
        with:
          commit: ${{ github.sha }}
          tag: Padavan
          artifacts: trunk/images/*.trx
          allowUpdates: true